#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <utility>
#include "../Ast/ast.hpp"

extern "C" {
	void yyerror(const char *);
	int yylex(void);
}

extern ASTNode* root;


#line 21 "parser.y"
typedef union {
	float num;
	char* str;
	bool boolean;
	class ASTNode* node; 
	class BlockNode* b_node;
	class ArgsList* args_l;
	class IDNode* id_node;
	class AssignFuncNode* ass_f_node;
	class LetAssign* ass_var;
	class VarAssignList* v_ass_l;
	class BoolExprNode* b_expr_node;
	class Conditional* cond;
	class WhileNode* while_node;
	class ForNode* for_node;
	class TypeDeclNode* t_node_decl;
	class ASTNodeVector* ast_node_v; 
	class VarAssign* var_ass;
	class AttributeMember* att_member;
	class MethodMember* meth_member;
	class AccessNode* acc_node;
	class VarAssignType* v_ass_t;
	class NewTypeNode* new_t_n;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUMBER	258
#define	BOOLEAN	259
#define	STRING	260
#define	ID	261
#define	PLUS	262
#define	MINUS	263
#define	TIMES	264
#define	DIV	265
#define	POW	266
#define	LPARENT	267
#define	RPARENT	268
#define	SEMICOLON	269
#define	COLON	270
#define	LKEY	271
#define	RKEY	272
#define	FUNCTION	273
#define	INLINE	274
#define	ASSIGN	275
#define	ASS_DES	276
#define	IF	277
#define	ELSE	278
#define	ELIF	279
#define	WHILE	280
#define	FOR	281
#define	ACCESS	282
#define	UMINUS	283
#define	TWOPOINTS	284
#define	NEW	285
#define	INHERITS	286
#define	IS	287
#define	AS	288
#define	GREATER_EQUAL	289
#define	GREATER	290
#define	LESS_EQUAL	291
#define	LESS	292
#define	EQUAL	293
#define	DISTINCT	294
#define	LET	295
#define	IN	296
#define	TYPE	297


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUMBER;
static const int BOOLEAN;
static const int STRING;
static const int ID;
static const int PLUS;
static const int MINUS;
static const int TIMES;
static const int DIV;
static const int POW;
static const int LPARENT;
static const int RPARENT;
static const int SEMICOLON;
static const int COLON;
static const int LKEY;
static const int RKEY;
static const int FUNCTION;
static const int INLINE;
static const int ASSIGN;
static const int ASS_DES;
static const int IF;
static const int ELSE;
static const int ELIF;
static const int WHILE;
static const int FOR;
static const int ACCESS;
static const int UMINUS;
static const int TWOPOINTS;
static const int NEW;
static const int INHERITS;
static const int IS;
static const int AS;
static const int GREATER_EQUAL;
static const int GREATER;
static const int LESS_EQUAL;
static const int LESS;
static const int EQUAL;
static const int DISTINCT;
static const int LET;
static const int IN;
static const int TYPE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUMBER=258
	,BOOLEAN=259
	,STRING=260
	,ID=261
	,PLUS=262
	,MINUS=263
	,TIMES=264
	,DIV=265
	,POW=266
	,LPARENT=267
	,RPARENT=268
	,SEMICOLON=269
	,COLON=270
	,LKEY=271
	,RKEY=272
	,FUNCTION=273
	,INLINE=274
	,ASSIGN=275
	,ASS_DES=276
	,IF=277
	,ELSE=278
	,ELIF=279
	,WHILE=280
	,FOR=281
	,ACCESS=282
	,UMINUS=283
	,TWOPOINTS=284
	,NEW=285
	,INHERITS=286
	,IS=287
	,AS=288
	,GREATER_EQUAL=289
	,GREATER=290
	,LESS_EQUAL=291
	,LESS=292
	,EQUAL=293
	,DISTINCT=294
	,LET=295
	,IN=296
	,TYPE=297


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUMBER=258;
const int YY_parse_CLASS::BOOLEAN=259;
const int YY_parse_CLASS::STRING=260;
const int YY_parse_CLASS::ID=261;
const int YY_parse_CLASS::PLUS=262;
const int YY_parse_CLASS::MINUS=263;
const int YY_parse_CLASS::TIMES=264;
const int YY_parse_CLASS::DIV=265;
const int YY_parse_CLASS::POW=266;
const int YY_parse_CLASS::LPARENT=267;
const int YY_parse_CLASS::RPARENT=268;
const int YY_parse_CLASS::SEMICOLON=269;
const int YY_parse_CLASS::COLON=270;
const int YY_parse_CLASS::LKEY=271;
const int YY_parse_CLASS::RKEY=272;
const int YY_parse_CLASS::FUNCTION=273;
const int YY_parse_CLASS::INLINE=274;
const int YY_parse_CLASS::ASSIGN=275;
const int YY_parse_CLASS::ASS_DES=276;
const int YY_parse_CLASS::IF=277;
const int YY_parse_CLASS::ELSE=278;
const int YY_parse_CLASS::ELIF=279;
const int YY_parse_CLASS::WHILE=280;
const int YY_parse_CLASS::FOR=281;
const int YY_parse_CLASS::ACCESS=282;
const int YY_parse_CLASS::UMINUS=283;
const int YY_parse_CLASS::TWOPOINTS=284;
const int YY_parse_CLASS::NEW=285;
const int YY_parse_CLASS::INHERITS=286;
const int YY_parse_CLASS::IS=287;
const int YY_parse_CLASS::AS=288;
const int YY_parse_CLASS::GREATER_EQUAL=289;
const int YY_parse_CLASS::GREATER=290;
const int YY_parse_CLASS::LESS_EQUAL=291;
const int YY_parse_CLASS::LESS=292;
const int YY_parse_CLASS::EQUAL=293;
const int YY_parse_CLASS::DISTINCT=294;
const int YY_parse_CLASS::LET=295;
const int YY_parse_CLASS::IN=296;
const int YY_parse_CLASS::TYPE=297;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		187
#define	YYFLAG		-32768
#define	YYNTBASE	43

#define YYTRANSLATE(x) ((unsigned)(x) <= 297 ? yytranslate[x] : 67)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     8,     9,    11,    13,    16,    19,    22,
    24,    26,    28,    31,    33,    35,    37,    39,    41,    45,
    48,    50,    54,    58,    66,    76,    85,    96,    97,    99,
   103,   107,   109,   114,   119,   126,   133,   139,   143,   149,
   153,   159,   167,   173,   174,   176,   178,   182,   186,   191,
   193,   197,   201,   205,   209,   213,   217,   220,   222,   226,
   230,   234,   238,   242,   246,   250,   254,   261,   268,   275,
   282,   289,   294,   299,   306,   315,   316,   319,   322,   327,
   334,   342,   352,   360,   370,   374
};

static const short yyrhs[] = {    47,
     0,    44,     0,    16,    45,    17,     0,     0,    46,     0,
    47,     0,    46,    47,     0,    48,    14,     0,    49,    14,
     0,    62,     0,    58,     0,    59,     0,    25,    61,     0,
     5,     0,    51,     0,    57,     0,    52,     0,    53,     0,
    51,    21,    48,     0,    22,    60,     0,    66,     0,    48,
    21,    48,     0,    48,    20,    48,     0,    18,     6,    12,
    50,    13,    19,    48,     0,    18,     6,    12,    50,    13,
    29,     6,    19,    48,     0,    18,     6,    12,    50,    13,
    16,    45,    17,     0,    18,     6,    12,    50,    13,    29,
     6,    16,    45,    17,     0,     0,    51,     0,    50,    15,
    51,     0,     6,    29,     6,     0,     6,     0,    40,    55,
    41,    48,     0,    40,    55,    41,    44,     0,    40,    51,
    20,    54,    41,    48,     0,    40,    51,    20,    54,    41,
    44,     0,    30,     6,    12,    56,    13,     0,    51,    20,
    48,     0,    51,    20,    48,    33,     6,     0,    51,    20,
    54,     0,    55,    15,    51,    20,    48,     0,    55,    15,
    51,    20,    48,    33,     6,     0,    55,    15,    51,    20,
    54,     0,     0,    48,     0,    54,     0,    56,    15,    48,
     0,    56,    15,    54,     0,     6,    12,    56,    13,     0,
     3,     0,    12,    48,    13,     0,    48,     7,    48,     0,
    48,     8,    48,     0,    48,     9,    48,     0,    48,    10,
    48,     0,    48,    11,    48,     0,     8,    48,     0,     4,
     0,    48,    34,    48,     0,    48,    35,    48,     0,    48,
    36,    48,     0,    48,    37,    48,     0,    48,    38,    48,
     0,    48,    39,    48,     0,    51,    32,     6,     0,    57,
    32,     6,     0,    12,    59,    13,    48,    23,    48,     0,
    12,    59,    13,    44,    23,    48,     0,    12,    59,    13,
    48,    23,    44,     0,    12,    59,    13,    44,    23,    44,
     0,    12,    59,    13,    48,    24,    60,     0,    12,    59,
    13,    44,     0,    12,    59,    13,    48,     0,    42,     6,
    50,    16,    63,    17,     0,    42,     6,    50,    31,     6,
    16,    63,    17,     0,     0,    63,    64,     0,    63,    65,
     0,    51,    20,    48,    14,     0,    51,    20,    48,    33,
     6,    14,     0,     6,    12,    50,    13,    19,    48,    14,
     0,     6,    12,    50,    13,    29,     6,    19,    48,    14,
     0,     6,    12,    50,    13,    16,    45,    17,     0,     6,
    12,    50,    13,    29,     6,    16,    45,    17,     0,     6,
    27,     6,     0,     6,    27,     6,    12,    56,    13,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    93,    95,    98,   102,   104,   107,   109,   112,   114,   115,
   118,   120,   121,   123,   124,   125,   126,   127,   128,   129,
   130,   131,   132,   135,   137,   138,   139,   142,   144,   145,
   148,   150,   153,   155,   158,   160,   163,   167,   169,   170,
   171,   172,   173,   176,   178,   179,   180,   181,   184,   188,
   190,   191,   192,   193,   194,   195,   196,   199,   201,   202,
   203,   204,   205,   206,   207,   208,   211,   213,   214,   215,
   216,   219,   221,   232,   234,   237,   239,   240,   243,   245,
   248,   250,   251,   252,   255,   257
};

static const char * const yytname[] = {   "$","error","$illegal.","NUMBER","BOOLEAN",
"STRING","ID","PLUS","MINUS","TIMES","DIV","POW","LPARENT","RPARENT","SEMICOLON",
"COLON","LKEY","RKEY","FUNCTION","INLINE","ASSIGN","ASS_DES","IF","ELSE","ELIF",
"WHILE","FOR","ACCESS","UMINUS","TWOPOINTS","NEW","INHERITS","IS","AS","GREATER_EQUAL",
"GREATER","LESS_EQUAL","LESS","EQUAL","DISTINCT","LET","IN","TYPE","input","lines_block",
"lines","non_empty_lines","line","expr","func_asign","args_list","id_expr","let_assign",
"var_ass_type","new_expr","var_assign_list","expr_list","func_call","arit_op",
"bool_expr","conditional","while_expr","type_node_decl","type_body_elements",
"attribute","method","member_access_expr",""
};
#endif

static const short yyr1[] = {     0,
    43,    43,    44,    45,    45,    46,    46,    47,    47,    47,
    48,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    48,    48,    49,    49,    49,    49,    50,    50,    50,
    51,    51,    52,    52,    53,    53,    54,    55,    55,    55,
    55,    55,    55,    56,    56,    56,    56,    56,    57,    58,
    58,    58,    58,    58,    58,    58,    58,    59,    59,    59,
    59,    59,    59,    59,    59,    59,    60,    60,    60,    60,
    60,    61,    61,    62,    62,    63,    63,    63,    64,    64,
    65,    65,    65,    65,    66,    66
};

static const short yyr2[] = {     0,
     1,     1,     3,     0,     1,     1,     2,     2,     2,     1,
     1,     1,     2,     1,     1,     1,     1,     1,     3,     2,
     1,     3,     3,     7,     9,     8,    10,     0,     1,     3,
     3,     1,     4,     4,     6,     6,     5,     3,     5,     3,
     5,     7,     5,     0,     1,     1,     3,     3,     4,     1,
     3,     3,     3,     3,     3,     3,     2,     1,     3,     3,
     3,     3,     3,     3,     3,     3,     6,     6,     6,     6,
     6,     4,     4,     6,     8,     0,     2,     2,     4,     6,
     7,     9,     7,     9,     3,     6
};

static const short yydefact[] = {     0,
    50,    58,    14,    32,     0,     0,     4,     0,     0,     0,
     0,     0,     2,     1,     0,     0,    15,    17,    18,    16,
    11,    12,    10,    21,    44,     0,     0,    57,     0,     0,
     5,     6,     0,     0,    20,     0,    13,    32,     0,     0,
    28,     0,     0,     0,     0,     0,     8,     0,     0,     0,
     0,     0,     0,     0,     0,     9,     0,     0,     0,     0,
    45,    46,     0,    85,    31,    51,     3,     7,    28,     0,
    12,    12,     0,     0,     0,     0,    29,    52,    53,    54,
    55,    56,    23,    22,    59,    60,    61,    62,    63,    64,
    19,    65,    66,     0,    49,     0,    44,     0,     0,     0,
    38,    40,     0,    34,    33,     0,    76,     0,    44,    47,
    48,     0,     0,     0,     0,    72,    73,     0,     0,     0,
    30,     0,     0,     0,    86,     4,     0,     0,     0,     0,
     0,    39,    36,    35,    41,    43,    32,    74,     0,    77,
    78,    76,    37,     0,    24,     0,    70,    68,    69,    67,
    71,     0,    28,     0,     0,    26,     4,     0,    42,     0,
     0,    75,     0,    25,     0,    79,     0,    27,     4,     0,
     0,     0,     0,     0,     0,    80,    83,    81,     4,     0,
     0,     0,    84,    82,     0,     0,     0
};

static const short yydefgoto[] = {   185,
    13,    30,    31,    32,    15,    16,    76,    17,    18,    19,
    62,    40,    63,    20,    21,    22,    35,    37,    23,   122,
   140,   141,    24
};

static const short yypact[] = {   115,
-32768,-32768,-32768,    -6,   204,   204,   155,    10,     7,    22,
    36,    53,-32768,-32768,   253,    49,     3,-32768,-32768,    35,
-32768,-32768,-32768,-32768,   166,    66,    74,-32768,   286,    65,
   155,-32768,    77,   204,-32768,   204,-32768,    61,    76,    -8,
    36,   204,   204,   204,   204,   204,-32768,   204,   204,   204,
   204,   204,   204,   204,   204,-32768,   204,    87,   104,   110,
   375,-32768,    68,   105,-32768,-32768,-32768,-32768,    36,   375,
   113,   116,   166,    36,   178,    -3,-32768,    67,    67,   117,
   117,   117,    91,    91,   408,   408,   408,   408,   408,   408,
    91,-32768,-32768,   118,-32768,   166,   166,    73,   178,   178,
   293,    95,   112,-32768,    91,    36,-32768,   128,   166,   375,
-32768,    90,    37,   119,   212,-32768,   375,   129,   178,   166,
-32768,    56,   122,    93,-32768,   155,   204,   133,   178,   178,
     7,-32768,-32768,    91,   326,-32768,    -4,-32768,   121,-32768,
-32768,-32768,-32768,   126,   375,    -2,-32768,   413,-32768,   413,
-32768,   139,    36,   204,    58,-32768,   155,   204,-32768,    94,
   245,-32768,   130,   375,    42,-32768,   142,-32768,   155,   204,
   144,   137,   135,   334,    -1,-32768,-32768,-32768,   155,   204,
   145,   367,-32768,-32768,   154,   156,-32768
};

static const short yypgoto[] = {-32768,
   -45,  -100,-32768,     5,    -5,-32768,   -66,    -9,-32768,-32768,
   -69,-32768,   -87,-32768,-32768,   -25,    33,-32768,-32768,    24,
-32768,-32768,-32768
};


#define	YYLAST		447


static const short yytable[] = {    28,
    29,    39,    98,   102,    14,    25,    74,   153,    71,   112,
    72,   106,   107,   157,   179,    33,   158,   180,    34,    61,
    26,   124,    27,-32768,    27,   144,   111,   108,    70,   104,
    70,    77,    75,    36,    58,    68,    78,    79,    80,    81,
    82,    38,    83,    84,    85,    86,    87,    88,    89,    90,
   136,    91,   126,   114,   116,   127,   163,   169,    41,    77,
   170,   137,    56,   137,   103,   128,    59,   101,   173,   105,
   171,    64,   138,   133,   162,    44,    45,    46,   181,    65,
    95,    67,    96,   147,   149,   113,   160,   106,    69,    27,
   110,    61,    92,   115,   117,    73,   121,    42,    43,    44,
    45,    46,   125,    61,    96,   143,   165,    96,   106,    93,
-32768,-32768,   139,   134,   135,    94,    97,     1,     2,     3,
     4,   145,     5,   148,   150,    99,     6,    46,   100,   109,
     7,   120,     8,   123,   132,-32768,     9,   142,   146,    10,
   154,   129,   156,    77,   159,   139,   168,   172,   161,   175,
   176,   177,   164,   186,    11,   187,    12,     1,     2,     3,
     4,   183,     5,   151,   174,   155,     6,     0,     1,     2,
     3,     4,     8,     5,   182,     0,     9,     6,     0,    10,
     1,     2,     3,     4,     0,     5,     0,     9,     0,     6,
    10,     0,     0,     7,    11,    60,    12,     0,     0,     9,
     0,     0,    10,     0,     0,    11,     1,     2,     3,     4,
     0,     5,     0,     0,     0,     6,     0,    11,    42,    43,
    44,    45,    46,     0,     0,     9,     0,     0,    10,     0,
     0,    48,    49,     0,   130,   131,     0,     0,     0,     0,
     0,     0,     0,    11,     0,    50,    51,    52,    53,    54,
    55,    42,    43,    44,    45,    46,     0,     0,   166,    42,
    43,    44,    45,    46,    48,    49,    47,     0,     0,     0,
     0,     0,    48,    49,     0,     0,     0,   167,    50,    51,
    52,    53,    54,    55,     0,     0,    50,    51,    52,    53,
    54,    55,    42,    43,    44,    45,    46,     0,    66,    42,
    43,    44,    45,    46,     0,    48,    49,     0,     0,     0,
     0,     0,    48,    49,     0,     0,     0,     0,     0,    50,
    51,    52,    53,    54,    55,   118,    50,    51,    52,    53,
    54,    55,    42,    43,    44,    45,    46,     0,     0,     0,
    42,    43,    44,    45,    46,    48,    49,   178,     0,     0,
     0,     0,     0,    48,    49,     0,     0,     0,   152,    50,
    51,    52,    53,    54,    55,     0,     0,    50,    51,    52,
    53,    54,    55,    42,    43,    44,    45,    46,     0,     0,
   184,    42,    43,    44,    45,    46,    48,    49,     0,     0,
     0,     0,     0,     0,    48,    49,     0,     0,     0,     0,
    50,    51,    52,    53,    54,    55,     0,     0,    50,    51,
    52,    53,    54,    55,    42,    43,    44,    45,    46,    42,
    43,    44,    45,    46,     0,     0,     0,    48,    49,     0,
     0,     0,    48,    49,     0,     0,     0,     0,     0,     0,
     0,-32768,-32768,-32768,-32768,-32768,-32768
};

static const short yycheck[] = {     5,
     6,    11,    69,    73,     0,    12,    15,    12,    34,    97,
    36,    15,    16,    16,    16,     6,    19,    19,    12,    25,
    27,   109,    29,    21,    29,   126,    96,    31,    34,    75,
    36,    41,    41,    12,    32,    31,    42,    43,    44,    45,
    46,     6,    48,    49,    50,    51,    52,    53,    54,    55,
   120,    57,    16,    99,   100,    19,   157,    16,     6,    69,
    19,     6,    14,     6,    74,    29,    32,    73,   169,    75,
    29,     6,    17,   119,    17,     9,    10,    11,   179,     6,
    13,    17,    15,   129,   130,    13,   153,    15,    12,    29,
    96,    97,     6,    99,   100,    20,   106,     7,     8,     9,
    10,    11,    13,   109,    15,    13,    13,    15,    15,     6,
    20,    21,   122,   119,   120,     6,    12,     3,     4,     5,
     6,   127,     8,   129,   130,    13,    12,    11,    13,    12,
    16,    20,    18,     6,     6,    41,    22,    16,     6,    25,
    20,    23,    17,   153,     6,   155,    17,     6,   154,     6,
    14,    17,   158,     0,    40,     0,    42,     3,     4,     5,
     6,    17,     8,   131,   170,   142,    12,    -1,     3,     4,
     5,     6,    18,     8,   180,    -1,    22,    12,    -1,    25,
     3,     4,     5,     6,    -1,     8,    -1,    22,    -1,    12,
    25,    -1,    -1,    16,    40,    30,    42,    -1,    -1,    22,
    -1,    -1,    25,    -1,    -1,    40,     3,     4,     5,     6,
    -1,     8,    -1,    -1,    -1,    12,    -1,    40,     7,     8,
     9,    10,    11,    -1,    -1,    22,    -1,    -1,    25,    -1,
    -1,    20,    21,    -1,    23,    24,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    40,    -1,    34,    35,    36,    37,    38,
    39,     7,     8,     9,    10,    11,    -1,    -1,    14,     7,
     8,     9,    10,    11,    20,    21,    14,    -1,    -1,    -1,
    -1,    -1,    20,    21,    -1,    -1,    -1,    33,    34,    35,
    36,    37,    38,    39,    -1,    -1,    34,    35,    36,    37,
    38,    39,     7,     8,     9,    10,    11,    -1,    13,     7,
     8,     9,    10,    11,    -1,    20,    21,    -1,    -1,    -1,
    -1,    -1,    20,    21,    -1,    -1,    -1,    -1,    -1,    34,
    35,    36,    37,    38,    39,    33,    34,    35,    36,    37,
    38,    39,     7,     8,     9,    10,    11,    -1,    -1,    -1,
     7,     8,     9,    10,    11,    20,    21,    14,    -1,    -1,
    -1,    -1,    -1,    20,    21,    -1,    -1,    -1,    33,    34,
    35,    36,    37,    38,    39,    -1,    -1,    34,    35,    36,
    37,    38,    39,     7,     8,     9,    10,    11,    -1,    -1,
    14,     7,     8,     9,    10,    11,    20,    21,    -1,    -1,
    -1,    -1,    -1,    -1,    20,    21,    -1,    -1,    -1,    -1,
    34,    35,    36,    37,    38,    39,    -1,    -1,    34,    35,
    36,    37,    38,    39,     7,     8,     9,    10,    11,     7,
     8,     9,    10,    11,    -1,    -1,    -1,    20,    21,    -1,
    -1,    -1,    20,    21,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    34,    35,    36,    37,    38,    39
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 94 "parser.y"
{ root = yyvsp[0].node; ;
    break;}
case 2:
#line 95 "parser.y"
{ root = yyvsp[0].node; ;
    break;}
case 3:
#line 99 "parser.y"
{ yyval.node = yyvsp[-1].b_node; ;
    break;}
case 4:
#line 103 "parser.y"
{ yyval.b_node = new BlockNode({}); ;
    break;}
case 5:
#line 104 "parser.y"
{ yyval.b_node = yyvsp[0].b_node; ;
    break;}
case 6:
#line 108 "parser.y"
{ yyval.b_node = new BlockNode({yyvsp[0].node}); ;
    break;}
case 7:
#line 109 "parser.y"
{ yyvsp[-1].b_node->add_child(yyvsp[0].node); yyval.b_node = yyvsp[-1].b_node; ;
    break;}
case 8:
#line 113 "parser.y"
{ yyval.node = yyvsp[-1].node; ;
    break;}
case 9:
#line 114 "parser.y"
{ yyval.node = yyvsp[-1].ass_f_node; ;
    break;}
case 10:
#line 115 "parser.y"
{ root = yyvsp[0].t_node_decl; ;
    break;}
case 11:
#line 119 "parser.y"
{ yyval.node = yyvsp[0].node; ;
    break;}
case 12:
#line 120 "parser.y"
{ yyval.node = yyvsp[0].b_expr_node; ;
    break;}
case 13:
#line 121 "parser.y"
{ yyval.node = yyvsp[0].while_node; ;
    break;}
case 14:
#line 123 "parser.y"
{ yyval.node = new StringNode(yyvsp[0].str); ;
    break;}
case 15:
#line 124 "parser.y"
{ yyval.node = yyvsp[0].id_node; ;
    break;}
case 16:
#line 125 "parser.y"
{ yyval.node = yyvsp[0].node; ;
    break;}
case 17:
#line 126 "parser.y"
{ yyval.node = yyvsp[0].ass_var; ;
    break;}
case 18:
#line 127 "parser.y"
{ yyval.node = yyvsp[0].v_ass_t; ;
    break;}
case 19:
#line 128 "parser.y"
{ yyval.node = new VarDesAssign(yyvsp[-2].id_node, yyvsp[0].node); ;
    break;}
case 20:
#line 129 "parser.y"
{ yyval.node = yyvsp[0].cond; ;
    break;}
case 21:
#line 130 "parser.y"
{ yyval.node = yyvsp[0].acc_node; ;
    break;}
case 22:
#line 131 "parser.y"
{ yyval.node = new BinOpNode(yyvsp[-2].node, ":=", yyvsp[0].node); ;
    break;}
case 23:
#line 132 "parser.y"
{ yyval.node = new BinOpNode(yyvsp[-2].node, "=", yyvsp[0].node); ;
    break;}
case 24:
#line 136 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-5].str), yyvsp[-3].args_l, yyvsp[0].node); ;
    break;}
case 25:
#line 137 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-7].str), yyvsp[-5].args_l, yyvsp[0].node, yyvsp[-2].str); ;
    break;}
case 26:
#line 138 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-6].str), yyvsp[-4].args_l, yyvsp[-1].b_node); ;
    break;}
case 27:
#line 139 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-8].str), yyvsp[-6].args_l, yyvsp[-1].b_node, yyvsp[-3].str); ;
    break;}
case 28:
#line 143 "parser.y"
{ yyval.args_l = new ArgsList({}); ;
    break;}
case 29:
#line 144 "parser.y"
{ yyval.args_l = new ArgsList({yyvsp[0].id_node}); ;
    break;}
case 30:
#line 145 "parser.y"
{ yyvsp[-2].args_l->add_child(yyvsp[0].id_node); yyval.args_l = yyvsp[-2].args_l; ;
    break;}
case 31:
#line 149 "parser.y"
{ yyval.id_node = new IDNode(yyvsp[-2].str, yyvsp[0].str); ;
    break;}
case 32:
#line 150 "parser.y"
{ yyval.id_node = new IDNode(yyvsp[0].str); ;
    break;}
case 33:
#line 154 "parser.y"
{ yyval.ass_var = new LetAssign(yyvsp[-2].v_ass_l->assigns, yyvsp[0].node); ;
    break;}
case 34:
#line 155 "parser.y"
{ yyval.ass_var = new LetAssign(yyvsp[-2].v_ass_l->assigns, yyvsp[0].node); ;
    break;}
case 35:
#line 159 "parser.y"
{ yyval.v_ass_t = new VarAssignType(yyvsp[-4].id_node->id_name, yyvsp[-2].new_t_n, yyvsp[0].node); ;
    break;}
case 36:
#line 160 "parser.y"
{ yyval.v_ass_t = new VarAssignType(yyvsp[-4].id_node->id_name, yyvsp[-2].new_t_n, yyvsp[0].node); ;
    break;}
case 37:
#line 164 "parser.y"
{ yyval.new_t_n = new NewTypeNode(yyvsp[-3].str, yyvsp[-1].ast_node_v->children); ;
    break;}
case 38:
#line 168 "parser.y"
{ yyval.v_ass_l = new VarAssignList({ new VarAssign(yyvsp[-2].id_node, yyvsp[0].node) }); ;
    break;}
case 39:
#line 169 "parser.y"
{ yyval.v_ass_l = new VarAssignList({ new VarAssign(yyvsp[-4].id_node, yyvsp[-2].node, yyvsp[0].str) }); ;
    break;}
case 40:
#line 170 "parser.y"
{ yyval.v_ass_l = new VarAssignList({ new VarAssign(yyvsp[-2].id_node, yyvsp[0].new_t_n)}); ;
    break;}
case 41:
#line 171 "parser.y"
{ yyvsp[-4].v_ass_l->add_child(new VarAssign(yyvsp[-2].id_node, yyvsp[0].node)); yyval.v_ass_l = yyvsp[-4].v_ass_l; ;
    break;}
case 42:
#line 172 "parser.y"
{ yyvsp[-6].v_ass_l->add_child(new VarAssign(yyvsp[-4].id_node, yyvsp[-2].node, yyvsp[0].str)); yyval.v_ass_l = yyvsp[-6].v_ass_l; ;
    break;}
case 43:
#line 173 "parser.y"
{ yyvsp[-4].v_ass_l->add_child(new VarAssign(yyvsp[-2].id_node, yyvsp[0].new_t_n)); yyval.v_ass_l = yyvsp[-4].v_ass_l; ;
    break;}
case 44:
#line 177 "parser.y"
{ yyval.ast_node_v = new ASTNodeVector({}); ;
    break;}
case 45:
#line 178 "parser.y"
{ yyval.ast_node_v = new ASTNodeVector({yyvsp[0].node}); ;
    break;}
case 46:
#line 179 "parser.y"
{ yyval.ast_node_v = new ASTNodeVector({yyvsp[0].new_t_n}); ;
    break;}
case 47:
#line 180 "parser.y"
{ yyvsp[-2].ast_node_v->add_child(yyvsp[0].node); yyval.ast_node_v = yyvsp[-2].ast_node_v; ;
    break;}
case 48:
#line 181 "parser.y"
{ yyvsp[-2].ast_node_v->add_child(yyvsp[0].new_t_n); yyval.ast_node_v = yyvsp[-2].ast_node_v; ;
    break;}
case 49:
#line 185 "parser.y"
{ yyval.node = new FunctionNode(yyvsp[-3].str, yyvsp[-1].ast_node_v); ;
    break;}
case 50:
#line 189 "parser.y"
{ yyval.node = new FloatNode(yyvsp[0].num); ;
    break;}
case 51:
#line 190 "parser.y"
{ yyval.node = yyvsp[-1].node; ;
    break;}
case 52:
#line 191 "parser.y"
{ yyval.node = new BinOpNode( yyvsp[-2].node, "+", yyvsp[0].node); ;
    break;}
case 53:
#line 192 "parser.y"
{ yyval.node = new BinOpNode( yyvsp[-2].node, "-", yyvsp[0].node); ;
    break;}
case 54:
#line 193 "parser.y"
{ yyval.node = new BinOpNode( yyvsp[-2].node, "*", yyvsp[0].node); ;
    break;}
case 55:
#line 194 "parser.y"
{ yyval.node = new BinOpNode( yyvsp[-2].node, "/", yyvsp[0].node); ;
    break;}
case 56:
#line 195 "parser.y"
{ yyval.node = new BinOpNode( yyvsp[-2].node, "^", yyvsp[0].node); ;
    break;}
case 57:
#line 196 "parser.y"
{ yyval.node = new UnaryOpNode("-", yyvsp[0].node); ;
    break;}
case 58:
#line 200 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BoolNode(yyvsp[0].boolean)); ;
    break;}
case 59:
#line 201 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, ">=", yyvsp[0].node)); ;
    break;}
case 60:
#line 202 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, ">", yyvsp[0].node)); ;
    break;}
case 61:
#line 203 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, "<=", yyvsp[0].node)); ;
    break;}
case 62:
#line 204 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, "<", yyvsp[0].node)); ;
    break;}
case 63:
#line 205 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, "==", yyvsp[0].node)); ;
    break;}
case 64:
#line 206 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, "!=", yyvsp[0].node)); ;
    break;}
case 65:
#line 207 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].id_node, "is", new IDNode(yyvsp[0].str))); ;
    break;}
case 66:
#line 208 "parser.y"
{ yyval.b_expr_node = new BoolExprNode(new BinOpNode(yyvsp[-2].node, "is", new IDNode(yyvsp[0].str))); ;
    break;}
case 67:
#line 212 "parser.y"
{ yyval.cond = new Conditional(yyvsp[-4].b_expr_node, yyvsp[-2].node, yyvsp[0].node); ;
    break;}
case 68:
#line 213 "parser.y"
{ yyval.cond = new Conditional(yyvsp[-4].b_expr_node, yyvsp[-2].node, yyvsp[0].node); ;
    break;}
case 69:
#line 214 "parser.y"
{ yyval.cond = new Conditional(yyvsp[-4].b_expr_node, yyvsp[-2].node, yyvsp[0].node); ;
    break;}
case 70:
#line 215 "parser.y"
{ yyval.cond = new Conditional(yyvsp[-4].b_expr_node, yyvsp[-2].node, yyvsp[0].node); ;
    break;}
case 71:
#line 216 "parser.y"
{ yyval.cond = new Conditional(yyvsp[-4].b_expr_node, yyvsp[-2].node, yyvsp[0].cond); ;
    break;}
case 72:
#line 220 "parser.y"
{ yyval.while_node = new WhileNode(yyvsp[-2].b_expr_node, yyvsp[0].node); ;
    break;}
case 73:
#line 221 "parser.y"
{ yyval.while_node = new WhileNode(yyvsp[-2].b_expr_node, yyvsp[0].node); ;
    break;}
case 74:
#line 233 "parser.y"
{ yyval.t_node_decl = new TypeDeclNode(new IDNode(yyvsp[-4].str), yyvsp[-3].args_l, yyvsp[-1].ast_node_v->children); ;
    break;}
case 75:
#line 234 "parser.y"
{ yyval.t_node_decl = new TypeDeclNode(new IDNode(yyvsp[-6].str), yyvsp[-5].args_l, yyvsp[-1].ast_node_v->children, {yyvsp[-3].str}); ;
    break;}
case 76:
#line 238 "parser.y"
{ yyval.ast_node_v = new ASTNodeVector({}); ;
    break;}
case 77:
#line 239 "parser.y"
{ yyvsp[-1].ast_node_v->add_child(yyvsp[0].var_ass); yyval.ast_node_v = yyvsp[-1].ast_node_v; ;
    break;}
case 78:
#line 240 "parser.y"
{ yyvsp[-1].ast_node_v->add_child(yyvsp[0].ass_f_node); yyval.ast_node_v = yyvsp[-1].ast_node_v; ;
    break;}
case 79:
#line 244 "parser.y"
{ yyval.var_ass = new VarAssign(yyvsp[-3].id_node, yyvsp[-1].node); ;
    break;}
case 80:
#line 245 "parser.y"
{ yyval.var_ass = new VarAssign(yyvsp[-5].id_node, yyvsp[-3].node, yyvsp[-1].str); ;
    break;}
case 81:
#line 249 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-6].str), yyvsp[-4].args_l, yyvsp[-1].node); ;
    break;}
case 82:
#line 250 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-8].str), yyvsp[-6].args_l, yyvsp[-1].node, yyvsp[-3].str); ;
    break;}
case 83:
#line 251 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-6].str), yyvsp[-4].args_l, yyvsp[-1].b_node); ;
    break;}
case 84:
#line 252 "parser.y"
{ yyval.ass_f_node = new AssignFuncNode(new IDNode(yyvsp[-8].str), yyvsp[-6].args_l, yyvsp[-1].b_node, yyvsp[-3].str); ;
    break;}
case 85:
#line 256 "parser.y"
{ yyval.acc_node = new AccessNode(yyvsp[-2].str, new AttributeMember(yyvsp[0].str)); ;
    break;}
case 86:
#line 257 "parser.y"
{ yyval.acc_node = new AccessNode(yyvsp[-5].str, new MethodMember(yyvsp[-3].str, yyvsp[-1].ast_node_v->children)); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 260 "parser.y"


void yyerror(const char *s) {
    fprintf(stderr, "Error: %s\n", s);
}